<?php

define('LIB4RI_NOTIF_MAIL_FORM_LINK', 'send_email');

/**
 * @file
 * Write some text here
 */
function lib4ri_notif_mail_help($path, $arg){
    switch ($path) {
        case "admin/help#lib4ri_notif_mail":
            return t("some help here");
            break;
    }
}

/**
 * Implements hook_block_info().
 */
function lib4ri_notif_mail_block_info(){
    $blocks['lib4ri_notif_mail'] = array(
        // The name that will appear in the block list.
        'info' => t('Notification e-mails'),
        // Default setting.
        'cache' => DRUPAL_NO_CACHE,
        'region' => 'sidebar_second',
        'status' => 1,
    );
    return $blocks;
}

/**
 * Implements hook_block_view().
 */
function lib4ri_notif_mail_block_view($delta = ''){
    switch ($delta) {
        case 'lib4ri_notif_mail':
            module_load_include('inc', 'lib4ri_notif_mail', 'includes/block');
            $object = menu_get_object('islandora_object', 2);
            if ($object && in_array('ir:citationCModel', $object->models)) {
                $block['subject'] = t('Lib4RI notification email');
                if (user_access('access content')) {
                    $result = [];
                    $block['content'] = lib4ri_notif_mail_get_block_links($object);
                }
            }
    }
    return $block;
}

/**
 * Implements hook_menu().
 */
function lib4ri_notif_mail_menu() {
    $items = array();
    $items[LIB4RI_NOTIF_MAIL_FORM_LINK] = array(
        'title' => 'Send email',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('lib4ri_notif_mail_form'),
        'access arguments' => array('lib4ri_notif_mail'),
        'file' => 'includes/lib4ri_notif_mail.form.inc',
    );
//     $items['send-mails/mailids'] = array(
//         'title' => 'Send Mails Autocomplete',
//         'page callback' => 'lib4ri_notif_mail_mailids_autocomplete',
//         'access arguments' => array('access content'),
//         'type' => MENU_CALLBACK,
//         'file' => 'lib4ri_notif_mail.query.inc',
//     );
    return $items;
}

/**
 * Implements hook_permission().
 */
function lib4ri_notif_mail_permission() {
    return array(
        'lib4ri_notif_mail' => array(
            'title' => t('Access notification'),
            'description' => t('User has permission for access the forms'),
        ),
        'advanced_lib4ri_notif_mail' => array(
            'title' => t('Access Advanced notification'),
            'description' => t('Advanced options like, Role based sending.'),
        ),
    );
}


/**
 * Implements hook_mail_alter().
 */
function lib4ri_notif_mail_mail_alter(&$message) {
    if (($message['module'] == 'lib4ri_notif_mail') && ($message['key'] = 'lib4ri_notif_mail_send')) {
        $message['headers'] = array(
            'MIME-Version' => '1.0',
            'Content-Type' => 'text/html; charset=UTF-8; format=flowed',
            'Content-Transfer-Encoding' => '8Bit',
            'X-Mailer' => 'Drupal',
            'Return-Path' => $message['from'],
        );
    }
}


